on:
  workflow_dispatch: 
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job ${{ github.job }}"
  job_02:
    runs-on:  ubuntu-latest
    needs: job_01
    steps:
      - run: "echo Job ${{ github.job }}"
  job_03:
    runs-on: ubuntu-latest
    needs: job_01
    steps:
      - run: "echo Job ${{ github.job }}"
  job_04:
    runs-on: ubuntu-latest
    needs: [job_02, job_03]
    steps:
      - run: "echo Job ${{ github.job }}"
